language: python
services:
  - 'docker'
python:
  - '3.6'
before_script: 'make build-docker'
script: 'make docker-build'
deploy:
    provider: 'pages'
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: 'docs/site/'
    on:
        branch: 'master'
